### ISSUE TITLE
Cant use parameter

### ISSUE THREAD

**Issue by kororro** [schellingb/ZillaLib#1]
At  https://github.com/schellingb/ZillaLib/blob/master/Source/ZL_PlatformSDL.cpp
line 171
argv0 = (argc ? argv[0] : NULL);

argv[0]  is  program's name, not a parameter.

Tried
argv0 = (argc > 1 ? argv[1] : NULL);

works with parameter, got segfault when there was no parameter.

**Comment by schellingb** [comment]
At line 171 of ZL_PlatformSDL.cpp we do want to store the program's name in the `argv0` variable. Because later when calling `ZL_LoadReleaseDesktopDataBundle` the framwork loads the asset data which are stored inside the program file directly.
You can disable the embedding of assets in the program file with the `Embed Assets in Binary` in the [project generator](https://zillalib.github.io/project-generator/). In that case you pass the path to the data bundle as a parameter to `ZL_LoadReleaseDesktopDataBundle` and then that `argv0` isn't used at all.

If you want to process parameters in your game application, you don't need to modify the library. The argc and argv are passed to the `Load` of your class that implements `ZL_Application` function.
