### ISSUE TITLE
Is VC6 still supported?

### ISSUE THREAD

**Issue by avelican** [schellingb/ZillaLib#17]
So I have been installing various ancient SDKs for the last 7 hours and I'm down to just 2 errors! SDL wants xinput.h from the DirectX 9 SDK. I read the last version of DX9 that works with VC6 is the Summer 2004 version, but it seems to be missing xinput.h. The 2010 version of the SDK does have it, but doesn't compile in VC6. Same story with dxgi.h.

Not sure where to go from here. Maybe my info was incorrect and I need a _slightly_ newer DX9 SDK?

I'm fairly new to this sort of thing, so sorry if I missed something obvious.

**Comment by avelican** [comment]
I was using the [project generator](https://zillalib.github.io/project-generator/).
Tried again with these zips, same two files missing: https://gist.github.com/avelican/3e7c181abc1ab6164a23bf0dba5f2756
```
...
...\zillalib\source\sdl\joystick\windows\sdl_dxjoystick_c.h(42) : fatal error C1083: Cannot open include file: 'xinput.h': No such file or directory
...
...\zillalib\source\sdl\video\windows\sdl_windowsvideo.c(250) : fatal error C1083: Cannot open include file: 'dxgi.h': No such file or directory
...
```

**Comment by schellingb** [comment]
Got you! Sorry for the first post, I somehow misread "xinput.h" as "xaudio.h" and then was completely off...

So it turns out 15 years or so ago when I installed VC6 I somehow installed a "Windows SDK 6.0A" and set the include/library directories in Visual C++ 6 to use it. That SDK includes "xinput.h" and "dxgi.h" which compiles with VC6. Now I couldn't find that SDK 6.0A for download anymore (apparently it was part of Visual Studio 2008) but I found [this thread](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/29e04ed3-7b14-4672-b0f9-897ef75e26fe/windows-sdk-60a?forum=windowssdk) which mentioned that the 6.1 SDK is a minor upgrade of 6.0A so that could maybe work.

I ended up a rabbit hole trying to find one of these old Windows SDK's publicly for download and I found ["6.0.6001.18000.367-KRMSDK_EN.iso" on the web archive](https://web.archive.org/web/20121219095921/https://www.microsoft.com/downloads/details.aspx?FamilyId=F26B1AA4-741A-433A-9BE5-FA919850BDBF) which contains the 6.1 SDK. I didn't want to run the original installer due to worrying it would break one of my existing working installations of Visual Studio so I extracted some cab files and renamed every file to their original file name and placed them into an "Include" and "Lib" directory. And VC6 didn't want to compile with them...

So I search some more and find ["6.1.6000.16384.10.WindowsSDK_Vista_Feb2007Update_rtm.DVD.Rel.iso" on Microsoft's site still available](https://www.microsoft.com/en-us/download/details.aspx?id=14477) which has the 6.0A SDK! So I created an `V6.0A\Include` directory and extract these cabs into it
- WinSDKBuild-SDK_Core_BLD_Common-common.0.cab
- WinSDKBuild-SDK_Core_BLD_Common-common.1.cab
- WinSDKBuild-SDK_Core_BLD_Common-common.2.cab
- WinSDKBuild-SDK_Core_BLD_Common-x86.0.cab
- WinSDKBuild-SDK_DirectShow_BLD_Common-common.0.cab
- WinSDKBuild-SDK_IE_BLD_Common-common.0.cab
- WinSDKBuild-SDK_IE_BLD_Common-x86.0.cab
- WinSDKBuild-SDK_IIS_BLD_Common-common.0.cab
- WinSDKBuild-SDK_MDAC_BLD_Common-common.0.cab
- WinSDKBuild-SDK_MSI_BLD_Common-common.0.cab
- WinSDKBuild-SDK_WMI_BLD_Common-common.0.cab
- WinSDKBuild-WinSDKBuild_VistaHeaders-common.0.cab
- WinSDKCompiler-WinSDKCompiler_VC8CppHeaders-common.0.cab => BUT ONLY THE FILE "sal.h"

Then I created `V6.0A\Lib` and extracted these cabs into it
- WinSDKBuild-SDK_DirectShow_BLD_X86-common.0.cab
- WinSDKBuild-SDK_IIS_BLD_X86-common.0.cab
- WinSDKBuild-SDK_MSI_BLD_X86-common.0.cab
- WinSDKBuild-SDK_WMI_BLD_X86-common.0.cab
- WinSDKBuild-WinSDKBuild_VistaLibs_X86-common.0.cab
- WinSDKBuild-WinSDKBuild_VistaLibs_X86-x86.0.cab

I renamed all files from `<NAME>_<EXT>.<GUID>` to `<NAME>.<EXT>` using the excellent [Siren](https://www.scarabee-software.net/en/siren.html) file renaming tool, set the Include and Lib directories as the top entry in the VC6 directories options and ... it compiles again! But with some warnings... So I added this on top of `WinNT.h` (after `#define _WINNT_`):
```c
#if (defined(_MSC_VER))
#if (_MSC_VER < 1300)
//VC6 pops warnings with new Windows SDK headers
#pragma warning (disable : 4035)
#endif
#endif
```
and also this on top of `WinGDI.h` (after `#define _WINGDI_`):
```c
#if (defined(_MSC_VER))
#if (_MSC_VER < 1300)
//VC6 pops warnings with new Windows SDK headers
#pragma warning (disable : 4068)
#endif
#endif
```
and VC6 is happy again. To spare you the annoyance of doing all that, here's that VC6 compatible V6.0A SDK for download: 
[Windows_SDK_V6.0A_for_VC6.zip](https://github.com/schellingb/ZillaLib/files/8333429/Windows_SDK_V6.0A_for_VC6.zip)

Just extract it somewhere (i.e. `C:\Program Files\Microsoft SDKs\Windows\V6.0A`), open the Options window in VC6, go to Directories and add the `V6.0A\Include` path to the top of the list of Include files and the `V6.0A\Lib` path to the top of Library files.

Hopefully this resolves your problems :-)

**Comment by avelican** [comment]
Hey, thanks so much! I got Hexzilla to build and run with the zip you provided.
Like you said the order of the includes is important, I had to put the V6.0A include above the VC98 include, otherwise it includes headers it can't compile.

For completeness sake, here's what I have now:

```
includes
C:\Program Files (x86)\Microsoft SDKs\Windows\V6.0A\Include
C:\Program Files (x86)\Microsoft Visual Studio\VC98\INCLUDE

libs
C:\Program Files (x86)\Microsoft SDKs\Windows\V6.0A\Lib
C:\Program Files (x86)\Microsoft Visual Studio\VC98\LIB
```

I removed MFC, ATL and February 2003 Platform SDK, and it still builds fine!
Thanks again :)
